cmd_/home/arch/langsdorff_kernel/tools/bpf/resolve_btfids/main.o := clang -Wp,-MD,/home/arch/langsdorff_kernel/tools/bpf/resolve_btfids/.main.o.d -Wp,-MT,/home/arch/langsdorff_kernel/tools/bpf/resolve_btfids/main.o -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89 -g -I/home/arch/langsdorff_kernel/tools/include -I/home/arch/langsdorff_kernel/tools/include/uapi -I/home/arch/langsdorff_kernel/tools/lib/bpf/ -I/home/arch/langsdorff_kernel/tools/lib/subcmd/ -D"BUILD_STR(s)=$(pound)s" -c -o /home/arch/langsdorff_kernel/tools/bpf/resolve_btfids/main.o main.c

source_/home/arch/langsdorff_kernel/tools/bpf/resolve_btfids/main.o := main.c

deps_/home/arch/langsdorff_kernel/tools/bpf/resolve_btfids/main.o := \
  /usr/include/stdio.h \
  /usr/include/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/bits/wordsize.h \
  /usr/include/bits/timesize.h \
  /usr/include/stdc-predef.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/long-double.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/lib/clang/22/include/stddef.h \
  /usr/lib/clang/22/include/__stddef_size_t.h \
  /usr/lib/clang/22/include/__stddef_null.h \
  /usr/lib/clang/22/include/stdarg.h \
  /usr/lib/clang/22/include/__stdarg___gnuc_va_list.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/bits/time64.h \
  /usr/include/bits/types/__fpos_t.h \
  /usr/include/bits/types/__mbstate_t.h \
  /usr/include/bits/types/__fpos64_t.h \
  /usr/include/bits/types/__FILE.h \
  /usr/include/bits/types/FILE.h \
  /usr/include/bits/types/struct_FILE.h \
  /usr/include/bits/types/cookie_io_functions_t.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/floatn.h \
  /usr/include/bits/floatn-common.h \
  /usr/include/bits/stdio.h \
  /usr/include/string.h \
  /usr/include/bits/types/locale_t.h \
  /usr/include/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /usr/include/unistd.h \
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/bits/getopt_posix.h \
  /usr/include/bits/getopt_core.h \
  /usr/include/bits/unistd_ext.h \
  /usr/include/linux/close_range.h \
  /usr/include/stdlib.h \
  /usr/lib/clang/22/include/__stddef_wchar_t.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/sys/types.h \
  /usr/include/bits/types/clock_t.h \
  /usr/include/bits/types/clockid_t.h \
  /usr/include/bits/types/time_t.h \
  /usr/include/bits/types/timer_t.h \
  /usr/include/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/endianness.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/uintn-identity.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/types/sigset_t.h \
  /usr/include/bits/types/__sigset_t.h \
  /usr/include/bits/types/struct_timeval.h \
  /usr/include/bits/types/struct_timespec.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/bits/thread-shared-types.h \
  /usr/include/bits/pthreadtypes-arch.h \
  /usr/include/bits/atomic_wide_counter.h \
  /usr/include/bits/struct_mutex.h \
  /usr/include/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-bsearch.h \
  /usr/include/bits/types/once_flag.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/libelf.h \
  /usr/lib/clang/22/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/bits/stdint-uintn.h \
  /usr/include/bits/stdint-least.h \
  /usr/include/elf.h \
  /usr/include/gelf.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/bits/struct_stat.h \
  /usr/include/bits/statx.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/linux/stat.h \
  /home/arch/langsdorff_kernel/tools/include/linux/types.h \
  /usr/lib/clang/22/include/stdbool.h \
  /usr/lib/clang/22/include/__stddef_header_macro.h \
  /usr/lib/clang/22/include/__stddef_ptrdiff_t.h \
  /usr/lib/clang/22/include/__stddef_offsetof.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/asm/bitsperlong.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/asm/../../../arch/x86/include/uapi/asm/bitsperlong.h \
  /home/arch/langsdorff_kernel/tools/include/asm-generic/bitsperlong.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/bits/statx-generic.h \
  /usr/include/bits/types/struct_statx_timestamp.h \
  /usr/include/bits/types/struct_statx.h \
  /usr/include/fcntl.h \
  /usr/include/bits/fcntl.h \
  /usr/include/bits/fcntl-linux.h \
  /usr/include/bits/types/struct_iovec.h \
  /usr/include/bits/cloexec.h \
  /usr/include/linux/falloc.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/linux/openat2.h \
  /usr/include/bits/openat2.h \
  /usr/include/errno.h \
  /usr/include/bits/errno.h \
  /usr/include/linux/errno.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/asm/errno.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/asm/../../../arch/x86/include/uapi/asm/errno.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/asm-generic/errno.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/asm-generic/errno-base.h \
  /usr/include/bits/types/error_t.h \
  /home/arch/langsdorff_kernel/tools/include/linux/rbtree.h \
  /home/arch/langsdorff_kernel/tools/include/linux/kernel.h \
  /usr/lib/clang/22/include/__stdarg_header_macro.h \
  /usr/lib/clang/22/include/__stdarg_va_list.h \
  /usr/lib/clang/22/include/__stdarg_va_arg.h \
  /usr/lib/clang/22/include/__stdarg___va_copy.h \
  /usr/lib/clang/22/include/__stdarg_va_copy.h \
  /usr/include/assert.h \
  /home/arch/langsdorff_kernel/tools/include/linux/build_bug.h \
  /home/arch/langsdorff_kernel/tools/include/linux/compiler.h \
  /home/arch/langsdorff_kernel/tools/include/linux/compiler-gcc.h \
  /usr/include/byteswap.h \
  /usr/include/linux/stddef.h \
  /home/arch/langsdorff_kernel/tools/include/linux/zalloc.h \
  /home/arch/langsdorff_kernel/tools/include/linux/err.h \
  /home/arch/langsdorff_kernel/tools/lib/bpf/btf.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/linux/btf.h \
  /home/arch/langsdorff_kernel/tools/lib/bpf/libbpf_common.h \
  /home/arch/langsdorff_kernel/tools/lib/bpf/libbpf.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/linux/bpf.h \
  /home/arch/langsdorff_kernel/tools/include/uapi/linux/bpf_common.h \
  /home/arch/langsdorff_kernel/tools/lib/subcmd/parse-options.h \

/home/arch/langsdorff_kernel/tools/bpf/resolve_btfids/main.o: $(deps_/home/arch/langsdorff_kernel/tools/bpf/resolve_btfids/main.o)

$(deps_/home/arch/langsdorff_kernel/tools/bpf/resolve_btfids/main.o):
