#ifndef __HYP_CONSTANTS_H__
#define __HYP_CONSTANTS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 */

#define STRUCT_HYP_PAGE_SIZE 4 /* sizeof(struct hyp_page) */
#define KVM_SHADOW_VM_SIZE 4976 /* sizeof(struct kvm_shadow_vm) */
#define SHADOW_VCPU_STATE_SIZE 9200 /* sizeof(struct shadow_vcpu_state) */

#endif
